### ISSUE TITLE
Is this working at all?

### ISSUE THREAD

**Issue by hbokh** [xavierbaude/VMware-coreos-multi-nodes-Kubernetes#2]
Hi Xavier,

I was wondering if this is working at all in a cluster-setup on your side...
I ask because there is no real functionality and upon researching issues I see this on the minions:

**journalctl -f**

```
Dec 13 12:39:07 k8s-minion-1 sdnotify-proxy[758]: E1213 12:39:07.770167 00001 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Dec 13 12:39:08 k8s-minion-1 sdnotify-proxy[758]: E1213 12:39:08.771522 00001 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
```

**flannel**

```
k8s-minion-1 ~ # systemctl status flanneld.service
● flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib64/systemd/system/flanneld.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: timeout) since Sun 2015-12-13 12:41:12 UTC; 2s ago
     Docs: https://github.com/coreos/flannel
  Process: 929 ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock /usr/bin/docker run --net=host --privileged=true --rm --volume=/run/flannel:/run/flannel --env=NOTIFY_SOCKET=/run/flannel/sd.sock --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --env-file=${FLANNEL_ENV_FILE} --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true (code=exited, status=0/SUCCESS)
  Process: 926 ExecStartPre=/usr/bin/touch ${FLANNEL_ENV_FILE} (code=exited, status=0/SUCCESS)
  Process: 923 ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR} (code=exited, status=0/SUCCESS)
  Process: 921 ExecStartPre=/usr/bin/mkdir -p /run/flannel (code=exited, status=0/SUCCESS)
  Process: 918 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
 Main PID: 929 (code=exited, status=0/SUCCESS)

Dec 13 12:41:12 k8s-minion-1 systemd[1]: Failed to start Network fabric for containers.
Dec 13 12:41:12 k8s-minion-1 systemd[1]: flanneld.service: Unit entered failed state.
Dec 13 12:41:12 k8s-minion-1 systemd[1]: flanneld.service: Failed with result 'timeout'.
```

**etcd-related**

On the master:

```
master ~ # etcdctl get coreos.com/network/config
{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}
```

On a minion:

```
k8s-minion-1 ~ # etcdctl get coreos.com/network/config
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: connection refused
error #1: dial tcp 127.0.0.1:2379: connection refused
```

So is this looking the same on your setup or have I made some foobar yet to be discovered...
Thank you - regards, Henk

**Comment by hbokh** [comment]
Also (in case you missed it) this is now possible in later version of CoreOS:

_The cloud-config `$private_ipv4` and `$public_ipv4` substitution variables are supported on VMWare in CoreOS releases 801.0.0 and greater._

See https://coreos.com/os/docs/latest/booting-on-vmware.html#cloud-config

**Comment by wixb50** [comment]
hello, i met the same issue with you ,have you ever fix it?

thanks a lot!!

**Comment by volvicoasis** [comment]
Hello,
Idem, 
etcd2 is running but :>
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: etcd member http://127.0.0.1:2379 has no leader
error #1: client: etcd member http://127.0.0.1:4001 has no leader

My master everything is OK. But my minion(s), I still working on it.

**Comment by bilak** [comment]
When I follow this guide I expect that ens192 interface on master node will have ip 10.0.1.30 as configured with `sed -i 's|$private_ipv4|10.0.1.30|g' user_data`. Hovewer this is not configured at all, instead of this dynamic ip is assigned to OS.
Is there any option how to configure static ip?

Thanks

**Comment by chadgates** [comment]
Error: client: etcd cluster is unavailable or misconfigured - same thing here... anyone has a fix for this so far ?

**Comment by aaratn** [comment]
Checking this in 2017. Seems like things have considerably changed ! Any plans to update this ?
